{% set name = "python-igraph" %}
{% set version = "0.7.1.post6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5ea42790a077eadb3d1e8f82edc47516fea4a2b26bbf52bfc148370fe0fe676

build:
  number: 1005
  script: python -m pip install --no-deps --ignore-installed .
  skip : true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - igraph 0.7.1
    - python
    - pip

  run:
    - igraph 0.7.1
    - pycairo >=1.10,<2
    - python

test:
  files:
    - test_cairo.py
    - test_graphml.py
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
    - igraph.test
    - igraph.vendor
  commands:
    - python -c 'from igraph.test import run_tests; run_tests()'
    - python test_cairo.py
    - python test_graphml.py

about:
  home: http://pypi.python.org/pypi/python-igraph
  license: GPL
  license_file: COPYING
  summary: 'High performance graph data structures and algorithms'

extra:
  recipe-maintainers:
    - sodre
