{% set name = "python-igraph" %}
{% set version = "0.7.1.post7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/igraph/python-igraph/archive/release-0.7.tar.gz
  sha256: 34a78ae458f30930f8ad1322d5bc13f3a3d2ef1aece6165717c49b326dcdb810

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip : true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - igraph 0.7.1
    - python
    - pip

  run:
    - igraph 0.7.1
    - pycairo >=1.10,<2
    - python

test:
  files:
    - test_cairo.py
    - test_graphml.py
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
    - igraph.test
    - igraph.vendor
  commands:
    - python -c 'from igraph.test import run_tests; run_tests()'
    - python test_cairo.py
    - python test_graphml.py

about:
  home: http://pypi.python.org/pypi/python-igraph
  license: GPL
  license_file: COPYING
  summary: 'High performance graph data structures and algorithms'

extra:
  recipe-maintainers:
    - sodre
