{% set name = "python-igraph" %}
{% set pypiname = "igraph" %}
{% set version = "0.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 6f9d8e1d6105b34298591820e94d4d8b3f33f38068523769e7a555bf7c96accb
  patches:
    - 0001-fix-remove-Py_LIMITED_API.patch

build:
  number: 1
  skip: true  # [win and vc<14]
  script_env:
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("python-igraph", max_pin="x.x") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - glpk
    - libxml2
    - suitesparse
    - arpack   # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - libblas
    - liblapack
    - python
    - pip
  run:
    - glpk
    - libxml2
    - suitesparse
    - arpack  # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - texttable >=1.6.2
    - python

test:
  source_files:
    - tests
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms
  dev_url: https://github.com/igraph/python-igraph
  doc_url: https://igraph.org/python/#docs

extra:
  recipe-maintainers:
    - sodre
    - vtraag
    - xylar
