{% set name = "python-igraph" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1895a83c57180f03c50fb77334a4d5029327aefee14f03381e10d34a1794410

build:
  number: 0
  skip: true  # [win and vc<14]
  script_env:
    - INTERNAL_ARPACK=0
    - INTERNAL_ARPACK=1  # [arm64]
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("python-igraph", max_pin="x.x") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config  # [not win]
    - pip
  host:
    - glpk
    - libxml2
    - suitesparse
    - arpack   # [not arm64]
    - gmp  # [not win]
    - mpir  # [win]
    - libblas
    - liblapack
    - python
  run:
    - glpk
    - libxml2
    - suitesparse
    - arpack  # [not arm64]
    - gmp  # [not win]
    - mpir  # [win]
    - texttable >=1.6.2
    - pycairo >=1.10,<2
    - python

test:
  source_files:
    - tests
  files:
    - test_cairo.py
    - test_graphml.py  # [not win]
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
  commands:
    - python -m unittest
    - python test_cairo.py
    - python test_graphml.py  # [not win]

about:
  home: https://igraph.org/python/
  license: GPL-2.0-or-later
  license_file:
    - COPYING
    - vendor/source/igraph/ACKNOWLEDGEMENTS.md
  summary: High performance graph data structures and algorithms

extra:
  recipe-maintainers:
    - sodre
    - vtraag
