travis:
  secure:
    BINSTAR_TOKEN: F+JUAQsvRsa+0tc5CrU5U8cQj3jKW45cWhiTKOMOUGD2aQKhtAj7YHhveW32nYrQO26gTbAAHMuu8h4Rr+diNdznaPwnrCCl7c4WJinO/X7DF3zFj4iyehvj+ucXGsOjv7PS6EYjpgFKwUUQGm8U9LAoZQHT9dezR00VuHAEtJPGPH7FXAclS5eLD5HBhVDOYa74WmyeU1b+TPn10YM3N8cSBup8+q2yTnTYHfivzawaBv/j4lXPZFKaux6xlg7fOiDF+vybKFYztyAzVQTtBTYjnGgWUUDGaNf83F/BRBxxsTMU7qF8uPf2mjj10BefgSs95k41bFxot5ZaY27G5D/fOSvhsxuHawEjTaYbs5u0GYzOQKouQlwYHryUcCCs3mnrs2IZeqZ24+rbRM5guBsR96BMHlXRJxkRyxsED+g6HSl4LDRMM2sujECmr8RA2KApOUEvbEG/6qZq+7rIQiVV6bKWC91XwuszHnGe/ULaLjhno3lKlgRKK0FPBSvCFcsQQHxjxafkhRdX5QeUVwHeLyDpqcsQchFwGNXht9PR6B+tztDSfpCd8QhHaIq4GuTS5fjNaKV/FaBWrb1fmMpSjeVghEcEDZl1vGraKsM8KQRz8MJEh4J8js6iXaXkxw6csVGb/cGNI6GsS4KvXJt5gBJG8OKGPGnWv4MWJZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
